version: "3"
services:
  test:
    build: advent
    working_dir: /app
    command: bash -c "watch mix test"
    volumes:
      - ./advent:/app
  day:
    build: advent
    working_dir: /app
    command: bash -c "./advent"
